### ISSUE TITLE
Issue about dataset

### ISSUE THREAD

**Issue by Rroscha** [vul337/jTrans#25]
Hello,
I have downloaded the provided BinaryCorp dataset. However, I found that the sizes of the train and test datasets are different from those mentioned in the paper. The downloaded train and test datasets have 37,183 and 9,351 binaries, but the paper says 38,455 and 9,675. Could you please clarify this? The link I used is https://cloud.vul337.team:9443/s/W57ZWXxn7zSKG4q.

Thank you.

**Comment by Hustcw** [comment]
I apologize for any inconvenience caused by the discrepancies in the dataset sizes. It's possible that some deduplication processes were applied to the dataset, resulting in a slight difference in the number of binaries compared to the numbers reported in the paper. Since it has been a considerable amount of time since the dataset was compiled, I'm unable to provide a precise explanation for this discrepancy. I'm sorry for any confusion this may have caused.

**Comment by Rroscha** [comment]
Okay, thanks a lot.
