### ISSUE TITLE
Are there plans to open source the pretraining code?

### ISSUE THREAD

**Issue by xunge** [vul337/jTrans#3]
Thank you very much for your work. I want to apply them to my own assembly code preprocessing scheme, so re-pretraining is required. Do you have plans to open source your pretrained code? Thanks a lot.

**Comment by Hustcw** [comment]
Thanks for your interest, @xunge! I will try to open source the pre-training code next month.

**Comment by xunge** [comment]
Dear author, is the pre-training code ready to be updated?

**Comment by Xzz132** [comment]
Dear author, now I really need your pre-training code to learn. If you can, can you open your preprocessed code? Thank you very much and look forward to your reply.

**Comment by Xzz132** [comment]
Dear author, now I really need your pre-training code to reference and apply to my solution. If so, can you open source your pre-training code? Thank you very much and look forward to your reply.

**Comment by Rijgersberg** [comment]
Any chance to get an update on this?

I realize cleaning up code to open source it is a lot of work and you might have different priorities right now. But anything you can release with little effort on your side would be great.

For example, it would already be very useful to just see a snippet of raw code for how you implemented the modified token and position embeddings,

**Comment by Hustcw** [comment]
Thank you for reaching out and expressing your interest in getting an update on the progress of our code release. We will release a new cross-architecture model and its pre-training code in the near future.

**Comment by Rijgersberg** [comment]
> Any chance to get an update on this?
> 
> I realize cleaning up code to open source it is a lot of work and you might have different priorities right now. But anything you can release with little effort on your side would be great.
> 
> For example, it would already be very useful to just see a snippet of raw code for how you implemented the modified token and position embeddings,

To answer my own question: it turns out that the implementation of the token and position embeddings is (cleverly?) done in a single line here: https://github.com/vul337/jTrans/blob/002952947ffbe3af1e53101f9007bb9142914c8f/finetune.py#L189C38-L189C38
```python
class BinBertModel(BertModel):
    def __init__(self, config, add_pooling_layer=True):
        super().__init__(config)
        self.config = config
        self.embeddings.position_embeddings=self.embeddings.word_embeddings
```

What this does is to completely ignore BERT's precomputed `position_embeddings` (a 512x768 matrix of sequence length x embedding length). Instead it points any calls to it to the first 512 positions in BERT's `word_embeddings` (a 2902x768 matrix of vocab length x embedding length).

Because of this, any calls or updates to the position embedding end up with the calls to the first 512 token word embeddings in the vocabulary. Which, very importantly, are exactly all the jump tokens.

In effect this makes the parameters shared: the position embeddings are learned by updates to the jump token word embeddings during pre-training.

See also the answer to https://github.com/vul337/jTrans/issues/11

**Comment by Brubbish** [comment]
> Thank you for reaching out and expressing your interest in getting an update on the progress of our code release. We will release a new cross-architecture model and its pre-training code in the near future.

Sorry to interrupt, is it available now.

**Comment by JasonCZH4** [comment]
I like your work! Is the pretraining code available now?

**Comment by Hustcw** [comment]
Sorry for this delay. We've released our new pre-train code at https://github.com/Hustcw/CEBin/tree/main/pretrain .
We also recommend trying our new approach CLAP with [model](https://huggingface.co/hustcw/clap-asm) and [code](https://github.com/Hustcw/CLAP). We've integrated our models into the online service at https://mlm.01.ai.
