### ISSUE TITLE
Hello, I have some questions about the chapter "real world vulnerability search"

### ISSUE THREAD

**Issue by crustsalt** [vul337/jTrans#4]
Hello, I want to try to reproduce the contents of the chapter "real world vulnerability search" in your paper, but I opened the data set used in your chapter. I found that the code is in TXT format and has no context (for example, direct compilation will show that there are many undefined user-defined functions). I want to ask you how to compile these codes and input these data into jtrans

**Comment by zeyugao** [comment]
Take [SecurityDataset.zip](https://github.com/SecretPatch/Dataset/blob/master/SecurityDataset.zip) as example. The txt files are named as `[CVE-id].[username].[repo-name].[commit-id]`. The content of the txt is the commit diff.

So, take `CVE-2018-9336.OpenVPN.openvpn.1394192b210cb3c6624a7419bcf3ff966742e79b.txt` as example.
This file means that `CVE-2018-9989` is a cve of https://github.com/OpenVPN/openvpn, and is fixed in https://github.com/OpenVPN/openvpn/commit/1394192b210cb3c6624a7419bcf3ff966742e79b

You can build openvpn with `CVE-2018-9989` unpatched with the following commands:

```bash
git clone https://github.com/OpenVPN/openvpn
cd openvpn
git checkout 1394192b210cb3c6624a7419bcf3ff966742e79b^  # Note the ^ here

# The following commands are the normal compilation process, and they are target-specific
autoreconf -f -i
./configure
make clean
make -j$(nproc)
```

**Comment by Nicholas-wei** [comment]
Hello, I also encountered problems reproducing the chapter "real world vulnerability search" in your paper. I have read your code, It's about comparing the same source code binaries with different log levels. But how can I change it to do vulnerability searches? Since the source code must be different.

**Comment by Hustcw** [comment]
Hello, in the vulnerability search section of our paper, we obtained the dataset by checking out the commit before the CVE patch, identifying the vulnerable functions, and compiling the project using different compilers and compilation options. This process allowed us to obtain a set of vulnerabilities associated with the same source code.
